#!/bin/sh

set -e

file="$(dirname "$(readlink -f "$0")")/secrets"

if [ -z "$1" ]
then
    printf 'Enter the name of your repository (e.g. lfairy/liana): '
    read name
else
    name="$1"
fi

if [ -f "$file" ] && grep -F "$name" "$file" >/dev/null
then
    echo "ERROR: $name already appears in secrets file!"
    exit 1
fi

secret="$(head -c 16 /dev/urandom | xxd -p)"

echo "$name $secret" >> "$file"
echo "Added $name to $file"

echo
echo "Your secret is:"
echo
echo "    $secret"
echo
echo "Now go to <https://github.com/$name/settings/hooks/new> and fill out the form."
