#!/bin/sh

set -e

dir="/srv/files/music"

if [ -d "$dir" ]; then
    cd "$dir"
    git fetch
    git checkout master
    git reset --hard origin/master
else
    mkdir -p "$dir"
    cd "$dir"
    git clone git@github.com:lfairy/music.git .
fi

make -j2
