#!/bin/sh

set -e

cd ~/nationstates

git fetch
git checkout master
git reset --hard origin/master

cabal clean
cabal configure
cabal haddock --hyperlink-source --html-location='https://hackage.haskell.org/package/$pkg-$version/docs'
rsync --recursive --delete dist/doc/html/nationstates /srv/doc
